### PR TITLE
Started with base API configuration

### PR DESCRIPTION
**Pull request by woojiahao**
Using Go and Chi to create the routing as Chi is simple and quick to setup.

For now:
- Setup server wrapper for Chi
- Setup database wrapper for MongoDB
- Create `Dockerfile` for deployments

### CODE REVIEW

**Comment by woojiahao** [comment]
Once the api is integrated with the `docker-compose.yml`, the pull request can be made

**Comment by woojiahao** [comment]
For the `api` service, the `network_mode` must be set to `host` to allow the `api` service to access the database as `localhost` since the container's network isn't isolated. More information [here.](https://docs.docker.com/network/host/)

**Review by khinshankhan — COMMENTED** [review]
Solid work, I was able to follow most of the code easily. My only concern is package paths like `github.com/woojiahao/pino/api/pkg/`, since technically the kkhan01 repository is considered 'canonical'. Does go mod take care of it so if I just clone `pino`, it treats the cloned version's api directory as `github.com/woojiahao/pino/api`? In which case it might be fine for these imports not to reference the canonical repository since it won't end up making a difference.

**Comment by woojiahao** [comment]
The path assigned doesn't change based on who clones it, it just references the parent repository that will house the changes. We can shift this repository to an organisation instead so the path can be `github.com/pino/pino/api`

**Comment by woojiahao** [comment]
Just to clarify, what I mean by "the parent repository that will house the change" is that Go Modules will use that GitHub path to pull changes. This means you can import other libraries just using this GitHub URL

**Review by khinshankhan — APPROVED** [review]

**Pull request merged**
